import 'package:flutter/material.dart';
const setAppColor = Color(0xFFf44336);
const double defaultPadding = 16.0;
const double padding8=8.0;
const double defaultImageSize=150;
const Color black12 = Colors.black12;
const Color white = Colors.white;
const Color black = Colors.black87;
const bigTittleSize = 16.0;
const normalTextSize = 13.0;
const smallSubtileSize =10.0;
const IconData heart = IconData(0xf442,);